services:
  frontend:
    image: streetfight-frontend
    environment:
      - API_URL=http://backend:8080
    ports:
      - "80:80"
      - "443:443"
  backend:
    image: streetfight-backend
    volumes:
     - "~/streetfight:/app/logs"