services:

  frontend:
    image: streetfight-frontend
    environment:
    - API_URL
    - WEBSITE_URL
    - XDG_CONFIG_HOME=/config
    - XDG_DATA_HOME=/data
    ports:
    - 80:80
    - 443:443
    volumes:
    - caddy_data:/data
    - caddy_config:/config

  backend:
    image: streetfight-backend
    environment:
    - DATABASE_URL
    - MAKE_DEBUG_ENTRIES
    - SECRET_KEY
    - WEBSITE_URL
    - LOG_LEVEL
    - LOG_OVERRIDES
    - GUNICORN_WORKERS
    - DEBUG
    volumes:
    - ./logs:/data/logs

  duckdns:
    image: lscr.io/linuxserver/duckdns
    environment:
    - TZ=Europe/London
    - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
    - TOKEN=${DUCKDNS_KEY}


volumes:
  caddy_data:
  caddy_config:
