services:
  frontend:
    image: streetfight-frontend
    environment:
    - API_URL=http://backend:8000
    ports:
    - 80:80
    - 443:443
  backend:
    image: streetfight-backend
    environment:
    - DATABASE_URL=sqlite:///data.db
    - MAKE_DEBUG_ENTRIES=true
    - SECRET_KEY=123321
    - WEBSITE_URL=http://houseabsolute.duckdns.org
    volumes:
    - ~/streetfight:/app/logs
